FROM node:18-bullseye

RUN apt-get update && \
    apt-get install -y openjdk-17-jre && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g allure-commandline

RUN java -version && allure --version

WORKDIR /allure


COPY displayreport.sh .

CMD [ "./displayreport.sh" ]