FROM mcr.microsoft.com/playwright:v1.57.0-noble

ENV DB_HOST=host.docker.internal \
    DB_USER=root \
    DB_PASSWORD=Naveen@123 \
    DB_DATABASE=users \
    DB_PORT=3308

WORKDIR /app

COPY package*.json .

RUN npm ci --only=production

COPY . .



CMD ["npm","run","test"]